apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/apiProtocol: REST
  labels:
    opendatahub.io/dashboard: "true"
  name: {{ include "vllm.fullname" . }}
spec:
  annotations:
    serving.knative.dev/progress-deadline: {{ .Values.runtime.timeout | default "30m" }}
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - name: kserve-container
      image: {{ .Values.runtime.image }}
      command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
      args:
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name={{`{{ .Name }}`}}' # need to escape braces for helm template
        # - --max-model-len
        # - "{{ .Values.runtime.maxModelLength }}"
        # - --gpu-memory-utilization
        # - "{{ .Values.runtime.gpuMemoryUtilization }}"
        # - --max-seq_len-to-capture
        # - "{{ .Values.runtime.maxSeqLength }}"
      env:
        - name: HF_HOME
          value: /tmp/hf_home
        - name: VLLM_LOGGING_LEVEL
          value: {{ .Values.runtime.logLevel | default "INFO" }}
      ports:
        - containerPort: 8080
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
